services:
  postgres:
    image: postgres:16
    container_name: kbo-postgres
    environment:
      POSTGRES_USER: kbo
      POSTGRES_PASSWORD: kbo
      POSTGRES_DB: kbo
    ports:
      - "1234:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./kbo-data:/kbo-data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend
  pgadmin:
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    env_file:
      - ./docker/pgadmin.env
    environment:
      TZ: "Europe/Paris"
    logging:
      driver: none
    ports:
      - 5050:80
    networks:
      - backend
    depends_on:
      - postgres
    volumes:
      - pgadmin-data:/var/lib/pgadmin

networks:
  backend:
volumes:
  pgadmin-data: